version: "3"
services:
  mysql:
    image: "mysql:8.0.30"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD = ${DB_ROOT_PASSWORD}
      - MYSQL_USER = ${DB_CUSTOM_USER}
      - MYSQL_PASSWORD = ${DB_PASSWORD}
      - MYSQL_DATABASE = ${DB_DATABASE}
